[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4"
prost = "0.5"
async-std = { version = "1.11.0", features = ["unstable"] }

[build-dependencies]
prost-build = "0.5"