[package]
name = "library"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4"
prost = "0.5"
async-std = { version = "1.11.0", features = ["unstable"] }
rmp-serde = "1.1.0"
serde = "1.0"
serde_derive = "1.0.137"

[build-dependencies]
prost-build = "0.5"